development:
  adapter: mysql2
  database: tutorial_development
  username: root
  password: th@dbr0ch1ll
  encoding: utf8
  host: 127.0.0.1
  port: 3306

test:
  adapter: mysql2
  database: tutorial_test
  username: root
  password: th@dbr0ch1ll
  encoding: utf8
  host: 127.0.0.1
  port: 3306
