development:
  adapter: mysql2
  database: tutorial_development
  username: root
  password: th@dbr0ch1ll
  encoding: utf8
  host: localhost
  port: 3306

test:
  adapter: mysql2
  database: tutorial_test
  username: root
  password: th@dbr0ch1ll
  encoding: utf8
  host: localhost
  port: 3306
